myfinance/finances/admin/urls.py
from django.conf.urls import url

from .views import (
    AdminMainView, AdminUserListView, AdminEditUserView, AdminDeleteUserView, AdminSearchUserView
)

urlpatterns = [
    url(r'^$', AdminMainView.as_view(), name='main'),
    url(r'^users/$', AdminUserListView.as_view(), name='user_list'),
    url(r'^delete/$', AdminDeleteUserView.as_view(), name='delete_user'),
    url(r'^edit/$', AdminEditUserView.as_view(), name='edit_user'),
    url(r'^search/$', AdminSearchUserView.as_view(), name='search_user'),
]

myfinance/finances/api/urls.py
from django.conf.urls import url

from .views import (
    AccountList, AccountDetail, ChargeList, ChargeDetail, StatisticsList, UserList, UserDetail
)

urlpatterns = [
    url(r'^accounts/$', AccountList.as_view(), name='account_list'),
    url(r'^accounts/(?P<number>\d+)/$', AccountDetail.as_view(), name='account_detail'),
    url(r'^accounts/(?P<number>\d+)/statistics/$', StatisticsList.as_view(), name='statistics'),
    url(r'^charges/$', ChargeList.as_view(), name='charge_list'),
    url(r'^charges/(?P<id>\d+)/$', ChargeDetail.as_view(), name='charge_detail'),
    url(r'^profile/$', UserList.as_view(), name='user_list'),
    url(r'^profile/(?P<username>\w+)/$', UserDetail.as_view(), name='user_detail'),
]

myfinance/finances/urls.py
from django.conf.urls import url

from .views import (
    MainPageView, AccountView, AddChargeView,
    AccountInsertView, AccountStatisticsView, LoginView, RegisterView,
    ProfileView, LogoutView, UserSearchView, PublicProfileView,
    AccountDeleteView, AccountEditView, DeleteChargeView, ReportView
)

urlpatterns = [
    url(r'^$', MainPageView.as_view(), name='main'),
    url(r'^insert/$', AccountInsertView.as_view(), name='insert'),
    url(r'^accounts/(?P<number>\d+)/$', AccountView.as_view(), name='account'),
    url(r'^accounts/(?P<number>\d+)/add/$', AddChargeView.as_view(), name='add_charge'),
    url(r'^accounts/(?P<number>\d+)/delete/$', DeleteChargeView.as_view(), name='delete_charge'),
    url(r'^accounts/(?P<number>\d+)/statistics/$', AccountStatisticsView.as_view(), name='statistics'),
    url(r'^accounts/(?P<number>\d+)/report/$', ReportView.as_view(), name='report'),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/$', ProfileView.as_view(), name="profile"),
    url(r'delete/$', AccountDeleteView.as_view(), name='delete'),
    url(r'edit/$', AccountEditView.as_view(), name='edit'),
    url(r'^user_search/$', UserSearchView.as_view(), name="user_search"),
    url(r'^profile/(?P<username>\w+)/$', PublicProfileView.as_view(), name='public_profile')
]

myfinance/myfinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', include("finances.admin.urls", namespace='admin')),
    url(r'^', include("finances.urls", namespace='finances')),
    url(r'^api/', include("finances.api.urls", namespace='api')),
    url(r'session_security/', include('session_security.urls')),
    url(r'^api-token-auth/', obtain_jwt_token)
]

myfinance/finances/admin/templates/main.html
{% extends "template_admin.html" %}
{% load bootstrap3 %}
{% block header %}
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1>Finance System Administration</h1>
        <p>This is an administration part of the site. Be happy that you succeeded accessing it. However, do not forget you are responsible for all your actions here.</p>
        <p><a class="btn btn-primary btn-lg" href="{% url "finances:register" %}" role="button">Register</a></p>
    </div>
    <div class="container marketing">
        <div class="row">
            <div class="col-lg-6">
                <h2>Managing users</h2>
                <p>You can edit or delete users and their data. Also you can look through accounts they possess.</p>
            </div>
            <div class="col-lg-6">
                <h2>Account data</h2>
                <p>You can look at account data of every user. You can find information about temporal account numbers and total sum of the account.</p>
            </div>
        </div>

    </div>
{% endblock %}

myfinance/finances/admin/templates/template_admin.html
{% load bootstrap3 %}
{% load static %}
{% load custom_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="{% static 'scripts/adminScript.js' %}"></script>
</head>
<body>
{% include 'session_security/all.html' %}
<nav role="navigation" class="navbar navbar-default">
    <div class="navbar-header">
        <a href="{% url "admin:main" %}" class="navbar-brand">Finance system</a>
    </div>
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li>
                <a href="{% url "admin:main" %}">
                    <i class="fa fa-home" aria-hidden="true"></i> Main page
                </a>
            </li>
            <li>
                <a href="{% url "admin:user_list" %}">
                    <i class="fa fa-user-circle-o" aria-hidden="true"></i> Users
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <form class="navbar-form navbar-left" method="get" action="{% url "admin:search_user" %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Search user">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            {% if request.user.is_authenticated %}
                <li><a href="{% url "finances:logout" %}">Log Out</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container-fluid">
    <div class="container-fluid">
        {% block header %}
        {% endblock %}
    </div>
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
</div>
<div class="navbar-fixed-bottom row-fluid">
    <div class="navbar-inner">
        <div class="container">
            <p class="pull-right"><a href="#">Back to top</a></p>
            <p>© 2016 Finance System, Inc. ·</p>
        </div>
    </div>
</div>
</body>
</html>

myfinance/finances/admin/templates/user_detail.html
{% extends "template_admin.html" %}
{% load bootstrap3 %}
{% block header %}
    <h1>{{ title }}</h1>
{% endblock %}
{% block content %}
    <div class="container-fluid">
    <div class="col-lg-6 col-md-6">
        <h4>Username: <b>{{ user.username }}</b></h4>
        {% if user.first_name == '' %}
            <h4><i>First Name: This user don't provide his first name.</i></h4>
        {% else %}
            <h4>First Name: <b>{{ user.first_name }}</b></h4>
        {% endif %}
        {% if user.last_name == '' %}
            <h4><i>Last Name: This user don't provide his last name.</i></h4>
        {% else %}
            <h4>Last Name: <b>{{ user.last_name }}</b></h4>
        {% endif %}
        <h4>Email: <b>{{ user.email }}</b></h4>
        <h4>Telephone: <b>{{ user.phone }}</b></h4>
        {% if user.address == None %}
            <h4><i>Address: This user don't provide his address.</i></h4>
        {% else %}
            <h4>Address: <b>{{ user.address }}</b></h4>
        {% endif %}
    </div>
        <div class="col-lg-6 col-md-6">
            {% ifnotequal accounts|length 0 %}
                <h3>User account list</h3>
            <table class="table">
            <tr>
                <th>
                    Number
                </th>
                <th>
                    Total sum
                </th>
            </tr>
                {% for acc in accounts %}
                    <tr>
                        <td>
                            {{ acc.number }}
                        </td>
                        <td>
                            {% if acc.total != None %}
                            {{ acc.total }}
                            {% else %}
                                <p>This account has no charges yet.</p>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
                <h3>This user has no accounts yet</h3>
            {% endifnotequal %}
        </div>
    </div>
{% endblock %}

myfinance/finances/admin/templates/user_list.html
{% extends "template_admin.html" %}
{% load bootstrap3 %}
{% block header %}
    <h1>{{ title }}</h1>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        {% bootstrap_messages %}
        <table class="table">
            <tr>
                <th>User name</th>
                <th>Phone number</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th>Address</th>
                <th>Latest log in</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            {% for user in users %}
                <tr id = "{{ user.id }}">
                    <td class='username'>{{ user.username }}</td>
                    <td class='phone'>+{{ user.phone.country_code }} {{ user.phone.national_number }}</td>
                    <td class='first_name'>{{ user.first_name }}</td>
                    <td class='last_name'>{{ user.last_name }}</td>
                    <td class='email'>{{ user.email }}</td>
                    <td class='address'>{{ user.address }}</td>
                    <td class='last_login'>{{ user.last_login }}</td>
                    <td><a><button id="edit{{ user.id }}" class="edit btn btn-warning">Edit user</button></a></td>
                    <td><a><button id="delete{{ user.username }}" class="delete btn btn-danger">Delete user</button></a></td>
                    <td><a href="/admin/search?username={{ user.username }}"><button class="find btn btn-info">Accounts</button></a></td>
                </tr>
            {% endfor %}
        </table>
        <nav aria-label="user-pager">
            <ul class="pager">
                {% if page_previous != None %}
                    <li class="previous"><a href="{% url "admin:user_list" %}?page={{ page_previous }}"><span aria-hidden="true">&larr;</span>Previous</a></li>
                {% endif %}
                {% if page_next != None %}
                    <li class="next"><a href="{% url "admin:user_list" %}?page={{ page_next }}">Next<span aria-hidden="true">&rarr;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
    <!-- Edit user form -->
    <div id="editUser" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Заголовок модального окна -->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Edit user data</h4>
                </div>
                <!-- Основное содержимое модального окна -->
                <div class="modal-body">
                    <form id="editForm" method="POST" action="/admin/edit/">
                        <legend id="username"></legend>
                        {% bootstrap_form form %}
                    </form>
                </div>
                <!-- Футер модального окна -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="sendEdit">Save</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete user form -->
    <div id="deleteUser" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Confirmation</h4>
                </div>
                <div class="modal-body">
                    Do you want to delete this user?
                    <form id="deleteForm" method="POST" action="/admin/delete/">
                        <input id="id_username" name="username" type="hidden" required="" value="">
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-primary" id="sendDelete" title="">Yes</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}