myfinance/finances/admin/urls.py
from django.conf.urls import url

from .views import (
    AdminMainView, AdminUserListView, AdminEditUserView, AdminDeleteUserView, AdminSearchUserView
)

urlpatterns = [
    url(r'^$', AdminMainView.as_view(), name='main'),
    url(r'^users/$', AdminUserListView.as_view(), name='user_list'),
    url(r'^delete/$', AdminDeleteUserView.as_view(), name='delete_user'),
    url(r'^edit/$', AdminEditUserView.as_view(), name='edit_user'),
    url(r'^search/$', AdminSearchUserView.as_view(), name='search_user'),
]

myfinance/finances/api/urls.py
from django.conf.urls import url

from .views import (
    AccountList, AccountDetail, ChargeList, ChargeDetail, StatisticsList, UserList, UserDetail
)

urlpatterns = [
    url(r'^accounts/$', AccountList.as_view(), name='account_list'),
    url(r'^accounts/(?P<number>\d+)/$', AccountDetail.as_view(), name='account_detail'),
    url(r'^accounts/(?P<number>\d+)/statistics/$', StatisticsList.as_view(), name='statistics'),
    url(r'^charges/$', ChargeList.as_view(), name='charge_list'),
    url(r'^charges/(?P<id>\d+)/$', ChargeDetail.as_view(), name='charge_detail'),
    url(r'^profile/$', UserList.as_view(), name='user_list'),
    url(r'^profile/(?P<username>\w+)/$', UserDetail.as_view(), name='user_detail'),
]

myfinance/finances/urls.py
from django.conf.urls import url

from .views import (
    MainPageView, AccountView, AddChargeView,
    AccountInsertView, AccountStatisticsView, LoginView, RegisterView,
    ProfileView, LogoutView, UserSearchView, PublicProfileView,
    AccountDeleteView, AccountEditView, DeleteChargeView, ReportView
)

urlpatterns = [
    url(r'^$', MainPageView.as_view(), name='main'),
    url(r'^insert/$', AccountInsertView.as_view(), name='insert'),
    url(r'^accounts/(?P<number>\d+)/$', AccountView.as_view(), name='account'),
    url(r'^accounts/(?P<number>\d+)/add/$', AddChargeView.as_view(), name='add_charge'),
    url(r'^accounts/(?P<number>\d+)/delete/$', DeleteChargeView.as_view(), name='delete_charge'),
    url(r'^accounts/(?P<number>\d+)/statistics/$', AccountStatisticsView.as_view(), name='statistics'),
    url(r'^accounts/(?P<number>\d+)/report/$', ReportView.as_view(), name='report'),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/$', ProfileView.as_view(), name="profile"),
    url(r'delete/$', AccountDeleteView.as_view(), name='delete'),
    url(r'edit/$', AccountEditView.as_view(), name='edit'),
    url(r'^user_search/$', UserSearchView.as_view(), name="user_search"),
    url(r'^profile/(?P<username>\w+)/$', PublicProfileView.as_view(), name='public_profile')
]

myfinance/myfinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', include("finances.admin.urls", namespace='admin')),
    url(r'^', include("finances.urls", namespace='finances')),
    url(r'^api/', include("finances.api.urls", namespace='api')),
    url(r'session_security/', include('session_security.urls')),
    url(r'^api-token-auth/', obtain_jwt_token)
]

myfinance/finances/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db.models import DateTimeField, CharField, DecimalField, ForeignKey, Model
from phonenumber_field.modelfields import PhoneNumberField


class UserProfile(AbstractUser):
    phone = PhoneNumberField(unique=True)
    address = CharField(max_length=100, null=True)


class Account(Model):
    number = CharField(unique=True, max_length=12, verbose_name="Account number", validators=[
        RegexValidator(
            r'^\d+$',
            message="Account number must contains only digits"
        ),
        RegexValidator(
            r'^[1-9]{1}\d{11}$',
            message="Account number must have precisely 12 digits and can not start with 0"
        )
    ])
    user = ForeignKey(UserProfile, related_name='accounts')

    def __str__(self):
        return str(self.number)


class Charge(Model):
    value = DecimalField(max_digits=8, decimal_places=2)
    transactedAt = DateTimeField(default=datetime.today)
    account = ForeignKey(Account)

    def __str__(self):
        return "( " + str(self.transactedAt) + " )" + " " + str(self.value) + " -> " + str(self.account)

myfinance/finances/admin/forms.py
from django.forms import ModelForm, HiddenInput
from phonenumber_field.widgets import PhoneNumberPrefixWidget

from ..models import UserProfile


class UserEditForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ["username", "email", "phone", "address", "first_name", "last_name"]
        widgets = {
            "phone": PhoneNumberPrefixWidget,
            "username": HiddenInput
        }

    def clean(self):
        username = self.cleaned_data.get('username')
        user = UserProfile.objects.get(username=username)
        phone_number = self.cleaned_data.get('phone')
        user_phone = UserProfile.objects.filter(phone=phone_number)
        if user is not None:
            if len(user_phone) == 0 or user_phone.get() == user:
                return self.cleaned_data
            else:
                self.add_error("phone", "This phone number is busy!")
        else:
            self.add_error("username", "There is no such object in database!")
        return self.cleaned_data


class UserDeleteForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ["username"]

    def clean(self):
        username = self.cleaned_data.get('username')
        user = UserProfile.objects.filter(username=username)
        if user is not None:
            return self.cleaned_data
        else:
            self.add_error("username", "There is no such user!")

myfinance/finances/admin/views.py
from decimal import Decimal
from functools import reduce

import requests
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, reverse
from django.views import generic

from .forms import UserEditForm, UserDeleteForm
from ..models import UserProfile


class AdminMainView(generic.TemplateView):
    template_name = 'main.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_staff:
            return render(request, self.template_name, {
                "title": "Main page"
            })
        raise PermissionDenied


class AdminUserListView(generic.TemplateView):
    template_name = "user_list.html"
    form_class = UserEditForm
    delete_form_class = UserDeleteForm

    def get(self, request, *args, **kwargs):
        if request.user.is_staff:
            user_list = UserProfile.objects.filter(is_staff=False)
            paginator = Paginator(user_list, 10)
            page_next = None
            page_previous = None
            page = request.GET.get('page')
            try:
                users = paginator.page(page)
                page_next = page - 1
                page_previous = page + 1
            except PageNotAnInteger:
                users = paginator.page(1)
                page_next = 2
                page_next = None
            except EmptyPage:
                users = paginator.page(paginator.num_pages)
                page_previous = paginator.num_pages - 1
                page_next = None
            return render(request, self.template_name, {
                'users': users,
                'page_next': page_next,
                'page_previous': page_previous,
                'form': self.form_class,
                'delete_form': self.delete_form_class
            })
        raise PermissionDenied


class AdminEditUserView(generic.View):
    form_class = UserEditForm

    def post(self, request):
        if request.user.is_staff:
            form = self.form_class(request.POST)
            if form.is_valid():
                headers = {'Authorization': 'JWT ' + request.session["token"]}
                username = form.cleaned_data['username']
                data = {
                    'first_name': form.cleaned_data['first_name'],
                    'last_name': form.cleaned_data['last_name'],
                    'email': form.cleaned_data['email'],
                    'address': form.cleaned_data['address'],
                    'phone': form.cleaned_data['phone'].country_code + form.cleaned_data['phone'].national_number,
                }
                put = requests.put(
                    "http://localhost:8000" + reverse("api:user_detail", args={username}),
                    data=data,
                    headers=headers
                )
                if put.status_code == 200:
                    success_message = "You have updated user data!"
                    messages.success(request, success_message)
                else:
                    error_message = "Something went wrong with the update :("
                    messages.error(request, error_message)
                return redirect(reverse("admin:user_list"))
            else:
                error_message = form.errors
                messages.error(request, error_message)
                return redirect(reverse("admin:user_list"))
        raise PermissionDenied


class AdminDeleteUserView(generic.View):
    form_class = UserDeleteForm

    def post(self, request):
        if request.user.is_staff:
            form = self.form_class(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("username")
                headers = {'Authorization': 'JWT ' + request.session["token"]}
                delete = requests.delete(
                    "http://localhost:8000" + reverse("api:user_detail", args={username}),
                    headers=headers
                )
                if delete.status_code == 204:
                    success_message = "The user " + username + " has been deleted successfully!"
                    messages.success(request, success_message)
                else:
                    error_message = "Something went wrong with the deleting"
                    messages.error(request, error_message)
            else:
                error_message = form.errors
                messages.error(request, error_message)
            return redirect(reverse("admin:user_list"))
        raise PermissionDenied


class AdminSearchUserView(generic.TemplateView):
    template_name = "user_detail.html"

    def get(self, request, *args, **kwargs):
        username = request.GET.get('username')
        headers = {'Authorization': 'JWT ' + request.session["token"]}
        get_user = requests.get(
            "http://localhost:8000" + reverse("api:user_list") + "?search=" + username,
            headers=headers
        )
        if get_user.status_code != 200:
            return render(request, '404.html')
        else:
            users = get_user.json()
            if len(users) != 1:
                return render(request, '404.html')
            else:
                user = users[0]
            headers = {'Authorization': 'JWT ' + request.session["token"]}
            response = requests.get(
                "http://localhost:8000" + reverse("api:account_list") + "?search=" + username,
                headers=headers
            )
            accounts = response.json()
            for elem in accounts:
                get_charges = requests.get(
                    "http://localhost:8000" + reverse("api:charge_list") + "?search=" + elem["number"],
                    headers=headers
                )
                account_charges = get_charges.json()
                if len(account_charges) == 0:
                    elem["total"] = None
                else:
                    elem["total"] = reduce(
                        lambda x, y: Decimal(x) + Decimal(y),
                        map(lambda x: x["value"], account_charges),
                        0.00
                    )
            return render(request, self.template_name, {
                "title": "User detail view",
                "user": user,
                "accounts": accounts
            })

myfinance/finances/api/views.py
from datetime import datetime, timedelta

from django.db.models import Sum
from django.db.models.functions import Extract
from pytz import UTC
from rest_framework.filters import SearchFilter
from rest_framework.generics import (
    ListAPIView, ListCreateAPIView, RetrieveUpdateDestroyAPIView
)
from rest_framework.response import Response
from rest_framework.views import APIView

from .permissions import IsAccountOwnerOrReadOnly, IsChargeOwner, IsHimself
from .serializers import (
    AccountDetailSerializer, AccountListSerializer, ChargeListSerializer, ChargeDetailSerializer,
    UserListSerializer, UserDetailSerializer, StatisticSerializer, FullUserDetailSerializer
)
from ..models import Account, Charge, UserProfile


class AccountList(ListCreateAPIView):
    queryset = Account.objects.all()
    serializer_class = AccountListSerializer
    filter_backends = [SearchFilter]
    search_fields = ['user__username']

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def get_queryset(self):
        if len(self.request.query_params) == 0:
            return Account.objects.filter(user=self.request.user)
        elif self.request.query_params.get('search', None) is not None:
            user = self.request.query_params.get('search', None)
            return Account.objects.filter(user__username=user)


class AccountDetail(RetrieveUpdateDestroyAPIView):
    queryset = Account.objects.all()
    serializer_class = AccountDetailSerializer
    lookup_field = 'number'
    permission_classes = [IsAccountOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save()


class ChargeList(ListCreateAPIView):
    queryset = Charge.objects.all()
    serializer_class = ChargeListSerializer
    filter_backends = [SearchFilter]
    search_fields = ['account__number']

    def get_queryset(self):
        if self.request.user.is_staff:
            if len(self.request.query_params) == 0:
                return Charge.objects.filter(account__user=self.request.user)
            elif self.request.query_params.get('search', None) is not None:
                account = self.request.query_params.get('search', None)
                return Charge.objects.filter(account__number=account)
        else:
            return Charge.objects.filter(account__user=self.request.user)


class ChargeDetail(RetrieveUpdateDestroyAPIView):
    queryset = Charge.objects.all()
    serializer_class = ChargeDetailSerializer
    lookup_field = 'id'
    permission_classes = [IsChargeOwner]


class StatisticsList(APIView):
    serializer_class = StatisticSerializer
    lookup_field = 'number'

    @staticmethod
    def get(request, number=None):
        content = {}
        if len(request.query_params) == 0:

            content = (Charge.objects
                       .filter(account__number=number)
                       .annotate(month=Extract('transactedAt', 'month'))
                       .values('month').annotate(total=Sum('value'))
                       .annotate(year=Extract('transactedAt', 'year'))
                       .values('year', 'month', 'total')
                       .order_by('year', 'month')
                       .values_list('year', 'month', 'total'))

        elif (request.query_params.get('date_from', None) and request.query_params.get('date_to', None)) is not None:

            date_from = (datetime.strptime(request.query_params.get('date_from'), '%Y-%m-%d')
                         .replace(tzinfo=UTC))
            date_to = ((datetime.strptime(request.query_params.get('date_to'), '%Y-%m-%d') + timedelta(days=1))
                       .replace(tzinfo=UTC))

            content = (Charge.objects
                       .filter(account__number=number, transactedAt__range=[date_from, date_to])
                       .annotate(month=Extract('transactedAt', 'month'))
                       .values('month').annotate(total=Sum('value'))
                       .annotate(year=Extract('transactedAt', 'year'))
                       .values('year', 'month', 'total')
                       .order_by('year', 'month')
                       .values_list('year', 'month', 'total'))

        return Response(content, status=200)


class UserList(ListAPIView):
    queryset = UserProfile.objects.all()
    serializer_class = UserListSerializer
    filter_backends = [SearchFilter]
    search_fields = ['username']

    def get_queryset(self):
        if len(self.request.query_params) == 0:
            return UserProfile.objects.filter(username=self.request.user)
        elif self.request.query_params.get('search', None) is not None:
            user = self.request.query_params.get('search')
            return UserProfile.objects.filter(username=user)


class UserDetail(RetrieveUpdateDestroyAPIView):
    queryset = UserProfile.objects.all()
    serializer_class = UserDetailSerializer
    lookup_field = 'username'
    permission_classes = [IsHimself]

    def perform_update(self, serializer):
        if self.request.user.is_staff:
            self.serializer_class = FullUserDetailSerializer
        serializer.save(user=self.request.user)

myfinance/finances/templates/account.html
{% extends "template.html" %}
{% load bootstrap3 %}
{% block header %}
    <div class="row">
        <h1>{{ title }}</h1>
    </div>
    <div class="row">
        <a href='{% url 'finances:statistics' number=account.number %}'>
            <button class="btn btn-info">
                <i class="fa fa-bar-chart" aria-hidden="true"></i> Look at your statistics
            </button>
        </a>
        <a href='{% url 'finances:add_charge' number=account.number %}'>
            <button class="btn btn-success">
                <i class="fa fa-exchange" aria-hidden="true"></i> Create new charge
            </button>
        </a>
    </div>
    <div class="row" style="padding-top: 10px">
        <a><button id="edit{{ account.id }}_{{ account.number }}" class="edit btn btn-success">
            <i class="fa fa-pencil fa-fw" aria-hidden="true"></i> Edit this account
        </button></a>
        <a><button id="delete{{ account.id }}_{{ account.number }}" class="delete btn btn-danger">
            <i class="fa fa-trash" aria-hidden="true"></i> Delete this account
        </button></a>
    </div>
{% endblock %}
{% block content %}
    <br/>
    <div class="row">{% bootstrap_messages %}</div>
    <div class="container-fluid">
        {% if not deposit|length_is:"0" or not withdraw|length_is:"0" %}
            <table class="left"><caption><h2>Your deposit operations</h2></caption>
                {% for charge in deposit %}
                    <tr>
                        <td>
                            {{ charge.transactedAt }}
                            <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                            {{ charge.value }}
                        </td>
                        <td>
                            <a>
                                <button id="{{ charge.id }}" class="delete-charge btn btn-danger">Delete</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <table class="right"><caption><h2>Your withdraw operations</h2></caption>
                {% for charge in withdraw %}
                    <tr>
                        <td>
                            {{ charge.transactedAt }}
                            <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                            {{ charge.value }}
                        </td>
                        <td>
                            <a>
                                <button id="{{ charge.id }}" class="delete-charge btn btn-danger">Delete</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <h2>There is no charges to display</h2>
        {% endif %}
    </div>
    <div id="deleteCharge" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Confirmation</h4>
                </div>
                <div class="modal-body">
                    <p>Do you want to delete this account?</p>
                    <form id="deleteChargeForm" method="POST" action="{% url "finances:delete_charge" number=account.number %}">
                        <input id="id_charge" name="charge" type="hidden" required="" value="">
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-primary" id="sendDeleteCharge" title="">Yes</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myfinance/finances/templates/account_list.html
{% ifnotequal accounts|length 0 %}
    <li class="dropdown">
        <a id="drop1" href="{% url "finances:profile" %}"
           class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-tasks" aria-hidden="true"></i> Account list
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            {% for acc in accounts %}
                <li>
                    <div class="row accountlist">
                        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                            <a class="alink" href="{% url 'finances:account' number=acc.number %}">{{ acc.number }}</a>
                            <b>
                                ({% if acc.total != None %}
                                    {{ acc.total }}
                                {% else %}
                                    empty
                                {% endif %})
                            </b>
                        </div>
                        <div id="buttons" class="col-xs-4 col-sm-4 col-md-4 col-lg-4" style="padding-left: 0">
                            <a><button id="edit{{ acc.id }}_{{ acc.number }}" class="edit btn btn-success">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </button></a>
                            <a><button id="delete{{ acc.id }}_{{ acc.number }}" class="delete btn btn-danger">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </button></a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </li>
{% else %}
    <li class="open">
        <a id="drop1" class="dropdown-toggle">
            <i class="fa fa-tasks"></i> Your accounts
        </a>
    </li>
{% endifnotequal %}

myfinance/finances/templates/add_charge.html
{% extends "template.html" %}
{% load bootstrap3 %}
{% block header %}
    <h1>{{ title }}</h1>
    <a href="{% url 'finances:account' number=account_number %}">
        <button id="" class="btn btn-primary">
            <i class="fa fa-arrow-left" aria-hidden="true"></i> Return to the account page
        </button>
    </a>
{% endblock %}
{% block content %}
    <br/>
    <div id="left-align" class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        {% bootstrap_messages %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button "Add new Charge" button_type="submit" button_class="btn-success" %}
        </form>
    </div>
{% endblock %}

myfinance/finances/templates/auth.html
{% extends "template.html" %}
{% load bootstrap3 %}
{% block header %}
    <h1>{{ title }}</h1>
{% endblock %}
{% block content %}
    {% bootstrap_messages %}
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <form method="post" action='{% url "finances:login" %}'>
            <legend>Enter you username and password</legend>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button "Log In" button_type="submit" button_class="btn-success" %}
        </form>
    </div>
{% endblock %}

myfinance/finances/templates/register.html
{% extends "template.html" %}
{% load bootstrap3 %}
{% block header %}
    <h1>{{ title }}</h1>
{% endblock %}
{% block content %}
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        {% bootstrap_messages %}
        <form method="post" action='{% url "finances:register" %}'>
            <legend>Enter your registration data here</legend>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button "Confirm" button_type="submit" button_class="btn-success" %}
        </form>
    </div>
{% endblock %}

myfinance/finances/templates/template.html
{% load bootstrap3 %}
{% load static %}
{% load custom_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% bootstrap_javascript jquery=1 %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.24/moment.min.js"></script>
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.24/daterangepicker.min.css">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.24/daterangepicker.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="{% static 'scripts/updateProfile.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/dateRangePicker.js' %}"></script>
    {{ form.media }}
</head>
<body>
    {% include 'session_security/all.html' %}
    <nav role="navigation" class="navbar navbar-default">
        <div class="navbar-header">
            <a href="{% url "finances:main" %}" class="navbar-brand">Finance system</a>
        </div>
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url "finances:main" %}">
                        <i class="fa fa-home" aria-hidden="true"></i> Main page
                    </a>
                </li>
                {% if request.user.is_authenticated and not request.user.is_staff %}

                    <li>
                        <a href='{% url "finances:profile" %}'>
                            <i class="fa fa-user-circle-o" aria-hidden="true"></i> Profile
                        </a>
                    </li>

                    {% show_accounts request %}

                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url "finances:login" %}">Log In</a></li>
                    <li><a href="{% url "finances:register" %}">Register</a></li>
                {% else %}
                    <form class="navbar-form navbar-left" method="get" action="{% url "finances:user_search" %}">
                        <div class="form-group">
                            <input type="text" class="form-control" name="username" placeholder="Search user">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    <li><a href="{% url "finances:logout" %}">Log Out</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="container-fluid">
            {% block header %}
            {% endblock %}
        </div>
        <div class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div id="deleteAccount" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Confirmation</h4>
                </div>
                <div class="modal-body">
                    <p>Do you want to delete this account?</p>
                    <form id="deleteForm" method="POST" action="{% url "finances:delete" %}">
                        <input id="id_number" name="number" type="hidden" required="" value="">
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-primary" id="sendDelete" title="">Yes</button>
                </div>
            </div>
        </div>
    </div>

    <div id="editAccount" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Confirmation</h4>
                </div>
                <div class="modal-body">
                    <p>Change your account number if you want:</p>
                    <form id="editForm" method="POST" action="{% url "finances:edit" %}">
                        <input id="id_path" name="path" type="hidden" required="" value="">
                        <input id="id_number" name="number" type="hidden" required="" value="">
                        <div class="form-group">
                            <label for="id_input">New account number</label>
                            <input class="form-control" id="id_input" name="input" type="text" required="" value="">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="sendEdit" title="">Edit</button>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar-fixed-bottom row-fluid">
        <div class="navbar-inner">
            <div class="container">
                <p class="pull-right"><a href="#">Back to top</a></p>
                <p>© 2016 Finance System, Inc. ·</p>
            </div>
        </div>
    </div>

</body>
</html>